name: Private actions test
on: push
jobs:
  Private_Actions_Test:
    runs-on: ubuntu-latest
    steps:
      #! Copying the repo into the VM
      - uses: actions/checkout@v2.4.0

      #! Using private ISSUE action
      - uses: "./.github/actions/issues"
        id: "issues"
        #! Input only accept strings
        with:
          token: ${{ secrets.USER_TOKEN }}
          # In a multiple commit push event
          # This syntax gets the OLDEST COMMIT
          title: ${{ github.event.commits[0].message }}
          # This syntax gets the YOUNGEST COMMIT
          #? title: ${{ github.event.commits[0].message }}
          body: "My body"
          assignees: "OKruel,OKruelNL"

      #! Input to the private action
      - name: "Input to the private action"
        # Notice the path ends in the folder that contains all necessary files to perfome the action
        uses: "./.github/actions/hello"
        # Gives an id for referencing this step in the next steps
        id: "hello"
        #! Input only accept strings
        with:
          who-to-greet: "Some person"

      #! Outputs of the private action
      - name: Output to the private action
        # To see the outputs options either dive into the code or print the step object first to check it.
        run: |
          echo "TIME: ${{ steps.hello.outputs.time }}"
          echo "JSVAR: $JSVAR"
          echo "ISSUE: ${{ steps.issues.outputs.issue }}"
          echo "EVENT OBJ: ${{ toJSON(github.event) }}"
