name: Continuos Integration
on:
  pull_request:
    branches: [develop]
  # When a pull resquest is approved it will generate a pull request
  # The "feature" branch will be pushed into development hence the push event in the develop branch
  push:
    branches: [develop]
jobs:
  Continuos_Integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up Node JS
        uses: actions/setup-node@v2.4.1
        with:
          node-version: "12.x"
      - name: Installing dependencies
        run: yarn preci && yarn ci
      - name: Checking prettier formating
        run: yarn prettier:check
      - name: Running tests with coverage
        run: yarn test -- --coverage
        env:
          CI: true
      - name: Build the Project
        if: ${{ github.event_name == 'push' }}
        run: yarn build
      - name: Deploy the Staging
        if: ${{ github.event_name == 'push' }}
        run: npx surge --project ./build --domain dry-rake.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
